# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns: 
          - "*"
  - package-ecosystem: "pip"
    directories:
      - "/"
      - "/backend"
      - "/backend/tests/unit"
    schedule:
      interval: "weekly"
    groups:
      python-packages:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/chat-app"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "tailwindcss"
        update-types: ["version-update:semver-major"]
    groups:
      npm-packages:
        patterns:
          - "*"
  - package-ecosystem: "docker"
    directories:
      - "/backend"
      - "/chat-app"
      - "/pipelines/ingestion"
    schedule:
      interval: "weekly"
    groups:
      docker-images:
        patterns:
          - "*"
