{{- if .Values.keycloak.enabled }}
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: {{ .Values.keycloak.namespace }}
spec:
  instances: 1
  db:
    vendor: postgres
    host: keycloak-db-rw.keycloak-operator.svc.cluster.local
    usernameSecret:
      name: keycloak-db-superuser
      key: username
    passwordSecret:
      name: keycloak-db-superuser
      key: password
  http:
    httpEnabled: true
    tlsSecret: keycloak-tls-secret
  hostname:
    hostname: {{ .Values.keycloak.hostname }}
  proxy:
    headers: xforwarded
{{- end }}