apiVersion: v1
kind: Namespace
metadata:
  name: keycloak-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-keycloak-operator
  namespace: keycloak-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  targetNamespaces:
  - "keycloak-operator"
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: keycloak-operator
  namespace: keycloak-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  channel: stable-v26.0
  name: rhbk-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace

