---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kong-cluster-cert
  namespace: ai-gateway
spec:
  encryptedData:
    tls.crt: AgBxkq3YhGUdlOPCXBl7ITWoPd4VlJJOPkDZQwMQVYdoyxHDZ5fMJ2YIRLXuX2ZTK1kNBKSBefNwXiJ0sIOyK/lniOnOBAqyFQm0QBVMdOv4XVKQslsvvLUFS27xEOFIhluxqpkVeHno7l/Oa8gRB9T5JuKwr68HKdXYtVbEvnvGeVqqNdeVrMRcikr9SjAf6S/aAmuMlRetpfppjOAICAl4xpU8WESF9QKllw+RyO4EcAgyvsnNQRuSsoqc68KmCO7ewOFTnLNtlMHpIknLluwaRtXV9Nn2nfuANP6TTMgXjwl6V4iK8gzCsCFbDElgi5uXqakzNcAuFsO2cESjFBR1V9kFsOyQ/9aiZMv7uPm1m5nxq6B66DZblJuSc10wLRnbrj4A+XLzqKEv5v9afOD9if4iYi7hbdtLPEC8+7kX6a3h2AdCOvmu20MKuoC6dskrYERP60iuIjADTd8tW6yq2D9/bMJHHVoTHD8qXSAcxzYJlMRC4n6hxTyAzmPEBZhBBZm7bZTCHPoZZxvL9FBAbw1goqIc8KWbQ2FA/ZUhGjRRz9Ee0RZkz2jh3Kdd4aq6eVFV0EL2qhV7jlBUzh6w/TXnOR9aBIMFosKQH/z8hirIthJgLAqpIU7XhKEmaXkeh0DUdpjOuO9LZ5ljhf0rn12W2FkYeZfHZhr9Nq0v4Qzz/uYCZuUvx364vfnfNNgd7+JK4IA1WjdMB8+dPGo5lKZ9YAAFD1U+CCg2zSXNUteCuOisNKC55DB3VViPTSPR8nh75+Z+EUt84puaofoF5Mk4sVGf5NybX2U5+34GA/DPkpH/x/3fhvhLGW11EvoxiPbd/g0tYkRhBvE/kgdd51ncsnf4EDghEvUtiW+URBKtCeFM/P9UOlCd9qqiPJCJZtCCR1vTocSXf3EQMIX7OOejVcMrWH0YzlLFYlaZdWvCKeoze03pJsVjlknVGAas1A9sK4nTvdqrTmrE8xHPcqBTImtEUkER7uMJgt8brtz3hhEkEBzTzY9eo0KSKwgXMNQznVH93Aa3glRvkIE1VGgarm2i58hSfSfYLmXt4vOruAWMBGd4h6Fh8FTG1gUCkFfTksS6ZlwU6Mbey7AqJn5ap2y43DBNaMsLS6Qg/PsaPTKcPcJsX5X0dnfkJ1qRkx+Pwcu9ddDGdOe4bJGOgAZA5cv7R6QdwTVVBuXIJw7ESGPJ/ABoFQ8J82fOl58s3r21mbenTlAFBiY0rk/4EWwFiAq8a0AdoCtSfku5RKKalUybH+O1BCFj6/ErUOTluxQMHoyTzVr2nJv9xBv7kL6PjACQ5DLvdhIC5Y7P6oDG39hgidtcERVFq6Hd7rXiHFo9Etbb8iGqI5gJdWiBrcbdLzt5ZxC6lteAsjg04kh9bkaR9MfQ3Z41FhkHaYrL+JniGduTGjf8FufEgdpPNzQoMcrooVpZggErJeA43XicDtwAbH7Bs6jY89ebem6QJKEk6r4LmSvWflL0CxRJyfh2O3sGaRazzl8oqek4a/rROx9FzpIE+7Fxqld/rpfBG+HSa5rYCTLo2vrHcxlIOs8ISIm3FAbUZcmxIApjIDRlHDYo/ziGY6F9MiNNivtqMa7vNLa8XREGa5gc2+ny1534ZioH3ODfDcEhMUcI17PkM1Wp4NpiBskqNlPPkax65dfs6ZUZ+N5uOxwsZpAIoZI+oTaz1UQzHKEqUvAm3DgZNrkKVSZyHSuFyJRAh0SXUrnYXAZKuoJollyFgLOjQOvF6Tr/NsoKyRLq7ps0l30xsn8UQha3fts94uVkgRE581VmtlU5LExLzJKWaT3Xfs4=
    tls.key: AgBSUn3pIAMHIOwUk9eVK6LcRut67rj+K/UH2kzE+o7Jmuq+zfZXOSy2ZcZfliGzfkgT2vxzxISdHSgoXDITZ38ZZSpKO1bmvjxiGuF2SUmfLlUjFYQxjGilDqrHwZOGmubvrtx4MwD25FM6NM8PGp9nrcVslJL+Ntj/TpMAOWsS6zAOcij3sbv41zzLKjlLOijhL+KiZPpxSMp++nlNHEICHlSLvFeqS7FSgo81KV9v1BMP+TUCNX4E2p/386+Tm3TQ0DslW22xg2icNMrhimUz4opHqkCBnAPBPOUbNbOQaPVPR3erCFGq/bYHMaIAkjC+apOGrsJ8y766EExM7shWvFZ9ZQGrTZu0P9GqeZruT26/VLp7cKd1z2A8OukypvoJUb5duFxzhjALbctarPTPEgApwSjT1XafhxQrnFNmtlT0IgNb+ZcK0+Z5VpNE4IyFWBbxe6/xGcRvaYkVWJwAytF/imqSLlV+vR5zk7MgPjMGBmoR+gIEYFeA2tKEkSQ/k0bJXpEPVv4MXNruLcaoPOEoHqG6pkgVh4bSrJgmsPQsovjCC/fWq09KydLgJwIwKplOSeaekh35s3fcv5JzyTlbOUfsUPFTwG5dqyub4ESgPCFlaAYkOzZK0VnjO86kyzNBGqxrKbJDr+N3ioVmu6V1X9UZ7WbAq9riVOsleTwZ3Ff5MohxzymY0iD+xE1NXn4z/oUXigSUUkaDUAORpvxaxr4HyARHTtNhyb4SAqHqPtPP05yAsQ6IFTZ0jtRn9E3y4dG+LrZXICBHD7x2RaZ1aybBHkidzZtzrxVCZw+EnvA1+TLHknTn9rbQEH8X1AFaGWXVWx6f4RsW2VgL06ZSmWQp3lo+jxJbPo6oYi6Ks7HizYSawBwR5TgfKpkYxl3vLtWJ2JROhYvEtLOtV7dajOndhsKUukV7lw/+MnLJhnNL6zsJVYXvDBl16mKfib8j/WaPjRvC/R3NZqz+8BHFzZZUDNWoKhi41E0qPB60M+HXQnCvcUgViN0gun7MxikX8CE5Q1JQF596okqTXCE=
  template:
    metadata:
      creationTimestamp: null
      name: kong-cluster-cert
      namespace: ai-gateway
    type: kubernetes.io/tls
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: ai-gateway
data:
  config.yaml: |
    _format_version: "3.0"
    plugins:
      # Plugin for OpenAI
      - config:
          auth:
            allow_override: false
          logging:
            log_payloads: true
            log_statistics: true
          max_request_body_size: 1048576
          model:
            name:
            options:
              max_tokens: 256
              temperature: 0.7
              top_p: 1.0
            provider: openai
          model_name_header: true
          response_streaming: allow
          route_type: llm/v1/chat
        enabled: true
        name: ai-proxy
        protocols:
          - http
          - https
        service: openai_service  # Tie plugin to OpenAI service

      # Plugin for Ollama
      - config:
          auth:
            allow_override: false
          logging:
            log_payloads: true
            log_statistics: true
          max_request_body_size: 1048576
          model:
            name:
            options:
              upstream_url: "http://192.168.1.79:11434/v1/chat/completions"  # Ollama backend endpoint
              max_tokens: 512
              temperature: 0.5
              top_p: 0.9
            provider: openai
          model_name_header: true
          response_streaming: allow
          route_type: llm/v1/chat
        enabled: true
        name: ai-proxy
        protocols:
          - http
          - https
        service: ollama_service  # Tie plugin to Ollama service

    services:
      # OpenAI Service
      - connect_timeout: 60000
        enabled: true
        host: localhost
        name: openai_service
        port: 30000
        protocol: http
        read_timeout: 60000
        retries: 5
        routes:
          - name: openai_route
            paths:
              - /openai
            protocols:
              - http
              - https
            strip_path: true
            preserve_host: false

      # Ollama Service
      - connect_timeout: 60000
        enabled: true
        host: localhost
        name: ollama_service
        port: 30001
        protocol: http
        read_timeout: 60000
        retries: 5
        routes:
          - name: ollama_route
            paths:
              - /ollama
            protocols:
              - http
              - https
            strip_path: true
            preserve_host: false
---
