apiVersion: batch/v1
kind: Job
metadata:
  name: kong-deck-sync
  namespace: ai-gateway
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  template:
    spec:
      containers:
        - name: deck
          image: kong/deck:latest
          command: ["deck"]
          args:
            - "gateway"
            - "sync"
            - "/config/config.yaml"
            - "--konnect-control-plane-name=ai-gateway"
            - "--konnect-token=$(KONNECT_TOKEN)"
          env:
            - name: KONNECT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kong-konnect-token
                  key: token
          volumeMounts:
            - name: kong-config
              mountPath: /config
      volumes:
        - name: kong-config
          configMap:
            name: kong-config
      restartPolicy: OnFailure
