apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg
  namespace: openshift-gitops  # Argo CD's namespace
spec:
  project: default
  sources:
    - chart: cloudnative-pg
      repoURL: https://cloudnative-pg.github.io/charts
      targetRevision: 0.22.1
    - repoURL: 'git@github.com:silexdatateam/ai-foundry-starter.git'
      targetRevision: HEAD
      path: vector-database/cnpg
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system  # The namespace to deploy into
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  # Allows Argo CD to create the namespace
      - ServerSideApply=true