apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vector-database
  namespace: openshift-gitops  # Argo CD's namespace
spec:
  project: default
  source:
    repoURL: 'git@github.com:silexdatateam/ai-foundry-starter.git'
    targetRevision: HEAD
    path: vector-database/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: pgvector  # The namespace to deploy into
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  # Allows Argo CD to create the namespace