apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nonroot-v2-scc-binding
  namespace: cnpg-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:nonroot-v2
subjects:
- kind: ServiceAccount
  name: cnpg-cloudnative-pg
  namespace: cnpg-system
