kind: KnativeEventing
apiVersion: operator.knative.dev/v1beta1
metadata:
  name: knative-eventing
  namespace: knative-eventing
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec: {}
